#pragma config(Sensor, in1,    potentLeft,     sensorPotentiometer)
#pragma config(Sensor, in2,    lfLeft,         sensorLineFollower)
#pragma config(Sensor, in7,    lfRight,        sensorLineFollower)
#pragma config(Sensor, in8,    potentRight,    sensorPotentiometer)
#pragma config(Sensor, dgtl1,  runningLED,     sensorLEDtoVCC)
#pragma config(Sensor, dgtl2,  warningLED,     sensorLEDtoVCC)
#pragma config(Sensor, dgtl11, stopBump,       sensorTouch)
#pragma config(Sensor, dgtl12, bottomLimit,    sensorTouch)
#pragma config(Motor,  port1,           flashlightLeft, tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           beltLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           paddleLeft,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           paddleRight,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           beltRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          flashlightRight, tmotorVexFlashlight, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "constants.c";
#include "basic-control.c";
#include "behaviors.c";

task haltDetection() {
	while (true) {
		if (SensorValue[stopBump] == 1) {
			warningOn(true);
			runningOn(false);
			stopAllTasks();
		}
	}
}

task main() {

	startTask(haltDetection);
	int detected;
	runningOn(true);
	warningOn(false);

	while (true) {
		elevator();
		detected = sense();
		paddle(detected);
		reset();
	}

}
