#pragma config(Sensor, in1,    potentLeft,     sensorPotentiometer)
#pragma config(Sensor, in2,    lfLeft,         sensorLineFollower)
#pragma config(Sensor, in7,    lfRight,        sensorLineFollower)
#pragma config(Sensor, in8,    potentRight,    sensorPotentiometer)
#pragma config(Sensor, dgtl1,  runningLED,     sensorLEDtoVCC)
#pragma config(Sensor, dgtl2,  warningLED,     sensorLEDtoVCC)
#pragma config(Sensor, dgtl11, stopBump,       sensorTouch)
#pragma config(Sensor, dgtl12, bottomLimit,    sensorTouch)
#pragma config(Motor,  port1,           flashlightLeft, tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           beltLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           paddleLeft,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           paddleRight,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           beltRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          flashlightRight, tmotorVexFlashlight, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Constants
const int MOTOR_MAX    = 127;
const int MOTOR_STOP   = 0;
const int BELT_SPEED   = floor(MOTOR_MAX / 3);
const int PADDLE_SPEED = floor(MOTOR_MAX / 2);
const int RESET_SPEED  = floor(PADDLE_SPEED / 2);
const int RIGHT_OK     = 0;
const int LEFT_OK      = 0;
const int LIGHT_ON     = -127;
const int LIGHT_OFF    = 0;
const int LED_ON       = 1;
const int LED_OFF      = 0;
const int SENSE_WAIT   = 1;
const int GREEN_LOW    = 9999;
const int GREEN_HI     = 9999;
const int ORANGE_LOW   = 9999;
const int ORANGE_HI    = 9999;
const int GREEN        = 1;
const int ORANGE       = 2;
const int CONTINGENCY  = GREEN;

void beltControl(float value) {
	motor[beltRight] = value;
	motor[beltLeft]  = value;
}

void flashlightControl(float value) {
	motor[flashlightLeft]  = value;
	motor[flashlightRight] = value;
}

void flashlightOn(bool status) {
	if (status) { flashlightControl(LIGHT_ON); }
	else { flashlightControl(LIGHT_OFF); }
}

void warningLEDControl(int value) {
	SensorValue[warningLED] = value;
}

void warningOn(bool status) {
	if (status) { warningLEDControl(LED_ON); }
	else { warningLEDControl(LED_OFF); }
}

void runningLEDControl(int value) {
	SensorValue[runningLED] = value;
}

void runningOn(bool status) {
	if (status) { runningLEDControl(LED_ON); }
	else { runningLEDControl(LED_OFF); }
}

void elevator() {

	while (SensorValue[bottomLimit] != 1) {
		beltControl(BELT_SPEED);
	}

	beltControl(MOTOR_STOP);

}

int sense() {
	int  senseValue;

	//while (true) {
	for(int rounds = 5; rounds > 0; rounds--) {

		flashlightOn(true);
		warningOn(false);
		wait1Msec(SENSE_WAIT * 1000);

		if (rounds % 2 == 0) { senseValue = SensorValue[lfLeft]; }
		else { senseValue = SensorValue[lfRight]; }

		wait1Msec(500);
		flashlightOn(false);

		if (senseValue < GREEN_HI &&
			  senseValue > GREEN_LOW)  {
			 return GREEN;
		} else if (senseValue < ORANGE_HI &&
			         senseValue > ORANGE_LOW)  {
			 return ORANGE;
		} else {
			warningOn(true);
		}

	}

	// After 5 attempts, if still unknown, deflect to default.
	return CONTINGENCY;

}

void stopPaddles() {
	motor[paddleLeft]  = 0;
	motor[paddleRight] = 0;
}

void paddle(int which) {
	if (which == GREEN) {
		motor[paddleLeft]  = PADDLE_SPEED;
	}	else if (which == ORANGE) {
		motor[paddleRight] = PADDLE_SPEED;
	}
	stopPaddles();
}

void reset() {

	bool leftStatus = false;
	bool rightStatus = false;

	while (!leftStatus && !rightStatus) {
		stopPaddles();

		leftStatus  = (SensorValue[potentLeft]  < LEFT_OK);
		rightStatus = (SensorValue[potentRight] < RIGHT_OK);

		if (!leftStatus) { motor[paddleLeft] = RESET_SPEED;	}
		if (!rightStatus) { motor[paddleRight] = RESET_SPEED;	}
	}
}

task haltDetection() {
	while (true) {
		if (SensorValue[stopBump] == 1) {
			warningOn(true);
			runningOn(false);
			stopAllTasks();
		}
	}
}

task main() {

	startTask(haltDetection);
	int detected;
	runningOn(true);
	warningOn(false);

	while (true) {
		elevator();
		detected = sense();
		paddle(detected);
		reset();
	}

}
