#pragma config(Sensor, in1,    lfLeft,         sensorLineFollower)
#pragma config(Sensor, in5,    lfMid,          sensorLineFollower)
#pragma config(Sensor, in8,    lfRight,        sensorLineFollower)
#pragma config(Sensor, dgtl1,  stopBump,       sensorTouch)
#pragma config(Sensor, dgtl2,  bottomLimit,    sensorTouch)
#pragma config(Sensor, dgtl7,  warningLED1,    sensorLEDtoVCC)
#pragma config(Sensor, dgtl8,  warningLED2,    sensorLEDtoVCC)
#pragma config(Sensor, dgtl9,  stopLED1,       sensorLEDtoVCC)
#pragma config(Sensor, dgtl10, stopLED2,       sensorLEDtoVCC)
#pragma config(Sensor, dgtl11, runningLED1,    sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, runningLED2,    sensorLEDtoVCC)
#pragma config(Motor,  port1,           flashlightLeft, tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           beltLeft,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           paddleLeft,    tmotorServoStandard, openLoop)
#pragma config(Motor,  port8,           paddleRight,   tmotorServoStandard, openLoop)
#pragma config(Motor,  port9,           beltRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          flashlightRight, tmotorVexFlashlight, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


#include "constants.c"
#include "basic-control.c"
#include "behaviors.c"

task haltDetection() {
	while (true) {
		if (SensorValue[stopBump] == 1) {
			warningOn(true);
			runningOn(false);
			stopAllTasks();
		}
	}
}

task main()
{
	/* while(true){ // jam
		wait1Msec(2000);
	}*/
startTask(haltDetection);
runningOn(true);
stopOn(false);

while(true) {
	reset();
	elevator();
	reset();
	paddle(GREEN);
}

while(true) {
	stopOn(true);
	runningOn(false);
}

}
